### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [NudeDude/Shitter#1]
Hi @NudeDude  Good day! I am a graphic artist and would like to contribute to your project by designing a logo for it. If you are interested and will give me permission I will begin designing asap. Hoping for your positive feedback. Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by NudeDude** [comment]
Hi @Tobaloidee it would be great if you could design a logo for my project. I would like to use it as an app icon.

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback! I will start designing now

**Comment by Tobaloidee** [comment]
Hi @NudeDude  here's what i came up with..still open for your suggestions particularly the color.. I hope you like it
![SHITTER pres-03](https://user-images.githubusercontent.com/36028424/55459598-8b73a700-5622-11e9-9574-7f80c2ae44d3.png)

**Comment by Tobaloidee** [comment]
Should I finalize my files and formats now then make a PR for it and also put it in the readme file?

**Comment by NudeDude** [comment]
Yes, I will integrate the new icon into the app and readme file

**Comment by Tobaloidee** [comment]
okay Sir..i will finish the files now and make a PR with it..👍

**Comment by Tobaloidee** [comment]
here's the PR #2 with the logo upload & readme update @NudeDude  

-you can download the files for adaptive icons and other formats [HERE](https://drive.google.com/drive/u/1/folders/1n1TBx-5gD7O7xBKbtgaIqOXY2P1pYDSv)

Thanks and best regards! 
- Tobaloidee

**Comment by NudeDude** [comment]
Thank you, @Tobaloidee  I just updated the app icon and it looks great :-)

**Comment by Tobaloidee** [comment]
You are welcome @NudeDude !!  I just checked your other projects and I am thinking if you also want me to to design logos for them? I would gladly do so. 👍

**Comment by NudeDude** [comment]
This would be great too :)
p.s. the name shitter is based on the name twitter

**Comment by Tobaloidee** [comment]
I opened an issue on your other project @NudeDude . Will close this issue now. :)
